import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import SideMenu from "./components/SideMenu";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <div className="sticky top-0 inset-x-0 z-50 group">
  <header className="relative h-12 mx-auto border-b duration-200  border-ui-border-base">
    <SideMenu/>
    </header>
        {children}
        </div></body>
    </html>
  );
}
