import type { Metadata } from "next";
import { Roboto } from 'next/font/google'
import "./globals.css";
import SideMenu from "./components/SideMenu";

 
const roboto = Roboto({
  weight: '400',
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: "INTRANINE",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={roboto.className}>
    
   <header className="z-300 h-12 fixed w-full">
    <SideMenu/>
    </header>
        {children}
        </body>
    </html>
  );
}
